baseURL = "https://stustanet.de/"
canonifyURLs = true
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
title = "StuStaNet e. V."
enableRobotsTXT = true
disableHugoGeneratorInject = true
disableKinds = ["RSS","taxonomy","taxonomyTerm"]
enableGitInfo = false
SectionPagesMenu = "main"

[params]
gitEditBaseUrl = "https://gitlab.stusta.de/stustanet/stustanet-website/edit/master/content/"

[Languages]
[Languages.de]
weight = 1
languageCode = "de-DE"
languageName = "Deutsch"

[[Languages.de.menu.main]]
weight = 1
name = "Home"
identifier = "home"
url = "/de/"

[[Languages.de.menu.main]]
weight = 2
name = "WLAN"
identifier = "wifi"
url = "/de/wifi/"

[[Languages.de.menu.main]]
weight = 3
name = "Verein"
identifier = "about"
url = "/de/about/"

[[Languages.de.menu.main]]
weight = 4
name = "Mitmachen"
identifier = "participate"
url = "/de/participate/"

[Languages.en]
weight = 2
languageCode = "en-US"
languageName = "English"

[[Languages.en.menu.main]]
weight = 1
name = "Home"
identifier = "home"
url = "/en/"

[[Languages.en.menu.main]]
weight = 2
name = "Wi-Fi"
identifier = "wifi"
url = "/en/wifi/"

[[Languages.en.menu.main]]
weight = 3
name = "About Us"
identifier = "about"
url = "/en/about/"

[[Languages.en.menu.main]]
weight = 4
name = "Participate"
identifier = "participate"
url = "/en/participate/"
