baseURL = "http://stustanet.zoidberg.stusta.de/"
canonifyURLs = true
defaultContentLanguage = "de"
title = "StuStaNet e.V."
enableRobotsTXT = true
disableHugoGeneratorInject = true
disableKinds = ["RSS","taxonomy","taxonomyTerm"]
enableGitInfo = false

[params]
gitEditBaseUrl = "https://gitlab.stusta.de/stustanet/stustanet-website/edit/master/content/"

[Languages]
[Languages.de]
weight = 1
languageCode = "de-DE"
languageName = "Deutsch"

[Languages.en]
weight = 2
languageCode = "en-US"
languageName = "English"
